name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 載入 Git 檔案 🛎️
        uses: actions/checkout@v2.3.1
          
      - name: 使用 Zip 📤
        uses: montudor/action-zip@v1

      - name: 製作 Zip 📥
        run: zip -qq -r build.zip .

      - name: 上傳 Zip 🚀
        uses: JantHsueh/upload-file-action@master
        with:
          url: ${{ vars.KIJYA_URL }}
          forms: '{"password":"${{ secrets.KIJYA_PASS }}","path":"${{ vars.KIJYA_PATH }}","cmd":"${{ vars.KIJYA_CMD }}"}'
          fileForms: '{"file":"build.zip"}'
